# suppress inspection "UnusedProperty" for whole file
spring.application.name=html-rest-api
spring.profiles.active=dev
springdoc.swagger-ui.path=/swagger
file.output.source=/tmp/index.html
website.title=Population Data